---
- name: Define hosts
  hosts: all

  pre_tasks:
    - name: Load config
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

    - name: Install Nix package manager
      ansible.builtin.import_role:
        name: ableton.nix

    - name: "Check installation of kubectl"
      ansible.builtin.command: "kubectl version --client"
      environment:
        PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
      register: package_check_cmd
      changed_when: false
      ignore_errors: true  

    - name: "Install nix package kubectl"
      ansible.builtin.command: "nix-env -iA nixpkgs.kubectl"
      environment:
        PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
      changed_when: true
      when: package_check_cmd.failed
